openapi: 3.0.0
info:
    title: Meeting Schduler
    description: Examples for API Test Plan
    version: 1.0.0
servers:
    - url: http://localhost
      description: Optional server description, e.g. Main (production) server
paths:
    /:
        get:
            summary: Find a meeting by the topic
            parameters:
                - name: topic
                  in: query
                  required: true
                  schema:
                      type: string
                      example: Weekly meeting
            responses:
                "200":
                    description: ok
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: integer
                                    topic:
                                        type: string
                                    date:
                                        type: string
                                    starttime:
                                        type: string
                                    length:
                                        type: integer
                "404":
                    description: Meeting not found
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: Meeting not found
        delete:
            summary: Deletes a meeting by the topic
            parameters:
                - name: topic
                  in: query
                  required: true
                  schema:
                      type: string
            responses:
                "200":
                    description: ok
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: Meeting cancelled
                "404":
                    description: Meeting not found
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: Meeting not found
    /schedule:
        post:
            summary: Schedule a new meeting
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                topic:
                                    type: string
                                date:
                                    type: string
                                starttime:
                                    type: string
                                length:
                                    type: integer
            responses:
                "201": # status code
                    description: Meeting created
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: integer
                                    topic:
                                        type: string
                                    date:
                                        type: string
                                    starttime:
                                        type: string
                                    length:
                                        type: integer
                "400":
                      description: Error
                      content:
                          application/json:
                              schema:
                                  type: object
                                  properties:
                                    message:
                                        type: string
                                        example: Meeting already scheduled 